from pathlib import Path
p = Path('tests/test_dashboard.js')
s = p.read_text()
old = '''test('관리자 톱니는 권한 확인 전 hidden 속성으로 감춘다', () => {\n  const indexHtml = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');\n  const authJs = fs.readFileSync(path.join(__dirname, '..', 'assets/js/core/auth.js'), 'utf8');\n  const stylesCss = fs.readFileSync(path.join(__dirname, '..', 'assets/css/styles.css'), 'utf8');\n  assert.match(indexHtml, /id="admin-page-link"[^>]*hidden/);\n  assert.match(authJs, /link\\.hidden = true/);\n  assert.match(authJs, /data\\?\\.is_admin === true\\) link\\.hidden = false/);\n  assert.match(stylesCss, /\\.dashboard-nav-actions \\[hidden\\]\\s*\\{\\s*display:none/);\n});'''
new = '''test('관리자 톱니는 권한 확인 전 hidden 속성으로 감춘다', () => {\n  const indexHtml = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');\n  const accountControls = fs.readFileSync(path.join(__dirname, '..', 'assets/js/core/account-controls.js'), 'utf8');\n  const stylesCss = fs.readFileSync(path.join(__dirname, '..', 'assets/css/styles.css'), 'utf8');\n  assert.match(indexHtml, /id="admin-page-link"[^>]*hidden/);\n  assert.match(accountControls, /link\\.hidden = true/);\n  assert.match(accountControls, /data\\?\\.is_admin === true\\) link\\.hidden = false/);\n  assert.match(stylesCss, /\\.dashboard-nav-actions \\[hidden\\]\\s*\\{\\s*display:none/);\n});'''
if old not in s:
    raise SystemExit('admin test block not found')
s = s.replace(old, new, 1)
old = '''test('개인설정 모달은 고정 헤더와 스크롤 본문에서 항상 닫을 수 있다', () => {\n  const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');\n  const styles = fs.readFileSync(path.join(__dirname, '..', 'assets/css/styles.css'), 'utf8');\n  const auth = fs.readFileSync(path.join(__dirname, '..', 'assets/js/core/auth.js'), 'utf8');\n  assert.match(html, /id="profile-modal"[\\s\\S]*role="dialog"[\\s\\S]*aria-modal="true"/);\n  assert.match(html, /class="profile-dialog[^\"]*"[\\s\\S]*class="profile-dialog-header[^\"]*"[\\s\\S]*id="profile-close-button"[\\s\\S]*class="profile-dialog-body"/);\n  assert.match(styles, /\\.profile-dialog \\{[\\s\\S]*?display:flex;[\\s\\S]*?max-height:min\\(44rem,calc\\(100svh - 2rem\\)\\);[\\s\\S]*?overflow:hidden;/);\n  assert.match(styles, /\\.profile-dialog-body \\{[\\s\\S]*?min-height:0;[\\s\\S]*?overflow-y:auto;/);\n  assert.match(styles, /@media \\(max-width:1023px\\)[\\s\\S]*?#profile-close-button \\{[\\s\\S]*?width:2\\.75rem;[\\s\\S]*?height:2\\.75rem;/);\n  assert.match(auth, /const closeProfileModal = \\(\\) => \\{[\\s\\S]*?profileModal\\.classList\\.add\\('hidden'\\)/);\n  assert.match(auth, /event\\.target === event\\.currentTarget\\) closeProfileModal\\(\\)/);\n  assert.match(auth, /event\\.key === 'Escape'[\\s\\S]*?closeProfileModal\\(\\)/);\n});'''
new = '''test('개인설정 모달은 고정 헤더와 스크롤 본문에서 항상 닫을 수 있다', () => {\n  const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');\n  const styles = fs.readFileSync(path.join(__dirname, '..', 'assets/css/styles.css'), 'utf8');\n  const accountControls = fs.readFileSync(path.join(__dirname, '..', 'assets/js/core/account-controls.js'), 'utf8');\n  assert.match(html, /id="profile-modal"[\\s\\S]*role="dialog"[\\s\\S]*aria-modal="true"/);\n  assert.match(html, /class="profile-dialog[^\"]*"[\\s\\S]*class="profile-dialog-header[^\"]*"[\\s\\S]*id="profile-close-button"[\\s\\S]*class="profile-dialog-body"/);\n  assert.match(styles, /\\.profile-dialog \\{[\\s\\S]*?display:flex;[\\s\\S]*?max-height:min\\(44rem,calc\\(100svh - 2rem\\)\\);[\\s\\S]*?overflow:hidden;/);\n  assert.match(styles, /\\.profile-dialog-body \\{[\\s\\S]*?min-height:0;[\\s\\S]*?overflow-y:auto;/);\n  assert.match(styles, /@media \\(max-width:1023px\\)[\\s\\S]*?#profile-close-button \\{[\\s\\S]*?width:2\\.75rem;[\\s\\S]*?height:2\\.75rem;/);\n  assert.match(accountControls, /const close = \\(\\) => \\{[\\s\\S]*?modal\\.classList\\.add\\('hidden'\\)/);\n  assert.match(accountControls, /event\\.target === event\\.currentTarget\\) close\\(\\)/);\n  assert.match(accountControls, /event\\.key === 'Escape'[\\s\\S]*?close\\(\\)/);\n});'''
if old not in s:
    raise SystemExit('profile modal test block not found')
s = s.replace(old, new, 1)
p.write_text(s)
