from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[1]


class EconomicChartFeatureTests(unittest.TestCase):
    def test_economic_chart_uses_one_large_switchable_chart(self):
        html = (ROOT / 'economic-charts.html').read_text(encoding='utf-8')
        script = (ROOT / 'assets/js/charts/economic-charts.js').read_text(encoding='utf-8')
        self.assertIn('경제지표 챠트', html)
        self.assertIn('id="economic-series-list"', html)
        self.assertIn('id="economic-chart-host"', html)
        self.assertNotIn('id="economic-sections"', html)
        self.assertIn('function renderList()', script)
        self.assertIn('selectSeries(m)', script)
        self.assertNotIn('function buildCard', script)

    def test_chart_starts_with_latest_300_and_uses_real_chart_space_right_gap(self):
        script = (ROOT / 'assets/js/charts/economic-charts.js').read_text(encoding='utf-8')
        css = (ROOT / 'assets/css/economic-charts.css').read_text(encoding='utf-8')
        html = (ROOT / 'economic-charts.html').read_text(encoding='utf-8')
        self.assertIn('DEFAULT_VISIBLE_BARS=300', script)
        self.assertIn('RIGHT_GAP_PX=18', script)
        self.assertIn('function rightGapBars()', script)
        self.assertNotIn('function updateFixedGap()', script)
        self.assertNotIn("chart.priceScale('right').width", script)
        self.assertIn('anchor=r.to>=last?maxTo:Math.min(r.to,maxTo)', script)
        self.assertIn('if(to>maxTo){to=maxTo;from=to-w;}', script)
        self.assertIn('showInitialRange()', script)
        self.assertIn("$('economic-fit-max').onclick=fitMax", script)
        self.assertIn('handleScale:{axisPressedMouseMove:false,mouseWheel:false,pinch:true}', script)
        self.assertIn('host.onwheel=wheel', script)
        self.assertIn('host.onwheel=null', script)
        self.assertIn('attributionLogo:false', script)
        self.assertNotIn('id="economic-plot-gap"', html)
        self.assertNotIn('.economic-plot-gap{', css)

    def test_series_list_reorders_and_persists_per_user_delete_restore(self):
        script = (ROOT / 'assets/js/charts/economic-charts.js').read_text(encoding='utf-8')
        css = (ROOT / 'assets/css/economic-charts.css').read_text(encoding='utf-8')
        self.assertNotIn('localStorage', script)
        self.assertIn("from('economic_chart_preferences')", script)
        self.assertIn('series_order', script)
        self.assertIn('hidden_series', script)
        self.assertIn('dragState.category!==name', script)
        self.assertIn('saveOrder(name,codes)', script)
        self.assertIn('function hideSeries(m)', script)
        self.assertIn('function restoreSeries()', script)
        self.assertIn('economic-series-remove', script)
        self.assertIn('economic-series-restore', script)
        self.assertIn('overflow-y:auto', css)
        self.assertIn('scrollbar-gutter:stable', css)
        hide_body = script.split('function hideSeries(m)', 1)[1].split('function restoreSeries()', 1)[0]
        self.assertNotIn("supabaseClient.from('economic_chart_points').delete", hide_body)

    def test_horizontal_line_has_one_combined_axis_marker_and_flat_bell(self):
        html = (ROOT / 'economic-charts.html').read_text(encoding='utf-8')
        script = (ROOT / 'assets/js/charts/economic-charts.js').read_text(encoding='utf-8')
        css = (ROOT / 'assets/css/economic-charts.css').read_text(encoding='utf-8')
        self.assertIn('id="economic-delete-line"', html)
        self.assertIn('id="economic-alert-modal"', html)
        self.assertIn('economic-alert-marker-box', script)
        self.assertIn('economic-alert-marker-value', script)
        self.assertIn('economic-alert-bell', script)
        self.assertIn('axisLabelVisible:false', script)
        self.assertIn('function schedulePlaceBells()', script)
        self.assertIn('requestAnimationFrame(()=>{bellPositionFrame=requestAnimationFrame(', script)
        self.assertIn('updateTickMode({from,to});schedulePlaceBells()', script)
        self.assertIn('chart.applyOptions({width:Math.max(1,host.clientWidth),height:Math.max(1,host.clientHeight)});schedulePlaceBells()', script)
        self.assertNotIn('economic-alert-price', script)
        self.assertNotIn('🔔', script)
        self.assertIn("source_type:'economic_chart'", script)
        self.assertIn("url:'economic-charts.html'", script)
        self.assertIn('css_selector:meta.code', script)
        self.assertIn('color:#d1d5db', css)
        self.assertIn('color:#facc15', css)
        marker_css = css.split('.economic-alert-marker-box{', 1)[1].split('}', 1)[0]
        self.assertNotIn('border-radius:50%', marker_css)
        self.assertIn("supabaseClient.from('targets').delete()", script)
        delete_line_body = script.split('function deleteLine()', 1)[1].split('function clearLines()', 1)[0]
        self.assertNotIn("from('targets')", delete_line_body)
        self.assertIn('horizontal_lines', script)
        self.assertIn('savePlainLinesFromChart()', script)
        self.assertIn('restorePlainLines()', script)
        self.assertIn('assets/js/charts/economic-charts.js?v=20', html)

    def test_crosshair_keeps_the_existing_marker_and_shows_its_raw_value_above_the_line(self):
        html = (ROOT / 'economic-charts.html').read_text(encoding='utf-8')
        script = (ROOT / 'assets/js/charts/economic-charts.js').read_text(encoding='utf-8')
        css = (ROOT / 'assets/css/economic-crosshair.css').read_text(encoding='utf-8')
        self.assertIn('id="economic-crosshair-value"', html)
        self.assertIn('function showCrosshairValue(param)', script)
        self.assertIn('param?.seriesData?.get(raw)', script)
        self.assertIn('chart.subscribeCrosshairMove(showCrosshairValue)', script)
        self.assertIn('host.onmouseleave=hideCrosshairValue', script)
        self.assertIn('function hideCrosshairValue()', script)
        self.assertIn('.economic-crosshair-value{position:absolute;top:6px', css)
        self.assertIn('background:#111827;color:#fff', css)

    def test_chart_footer_is_compact_and_date_axis_is_korean(self):
        css = (ROOT / 'assets/css/economic-charts.css').read_text(encoding='utf-8')
        script = (ROOT / 'assets/js/charts/economic-charts.js').read_text(encoding='utf-8')
        self.assertIn('height:min(64.8vw,calc(90dvh - 162px));min-height:324px', css)
        self.assertIn('.economic-chart-panel{display:flex;min-width:0;min-height:0;height:100%', css)
        self.assertIn('.economic-chart-host{position:relative;box-sizing:border-box;width:100%;min-width:0;min-height:0;flex:1 1 auto', css)
        self.assertIn('height:min(423px,58.5dvh);min-height:270px', css)
        self.assertIn('min-height:24px', css)
        self.assertIn('padding:4px 12px 6px', css)
        self.assertIn("locale:'ko-KR'", script)
        self.assertIn("dateFormat:'yyyy. MM. dd.'", script)
        self.assertIn('tickMarkFormatter:koTick', script)
        self.assertIn('return`${p.year}년`', script)
        self.assertIn('return`${p.month}월`', script)
        self.assertIn("if(!monthTickDates.has(timeKey(time)))return''", script)

    def test_visible_values_use_the_shared_two_decimal_formatter(self):
        script = (ROOT / 'assets/js/charts/economic-charts.js').read_text(encoding='utf-8')
        core = (ROOT / 'assets/js/core/frontend-core.js').read_text(encoding='utf-8')
        self.assertIn('function formatDisplayNumber', core)
        self.assertIn('Math.min(2,Math.max(0,Number(m?.decimals)||0))', script)
        self.assertIn("type:'custom'", script)
        self.assertIn('formatter:value=>window.MacroWatchFrontend.formatDisplayNumber', script)
        self.assertNotIn('Number(v).toFixed(m.decimals)', script)

    def test_moving_averages_do_not_add_current_value_axis_labels(self):
        script = (ROOT / 'assets/js/charts/economic-charts.js').read_text(encoding='utf-8')
        self.assertIn("D:[5,20,'5일','20일']", script)
        self.assertIn("W:[4,26,'4주','26주']", script)
        self.assertIn("T:[6,18,'6구간','18구간']", script)
        self.assertIn("M:[6,24,'6개월','24개월']", script)
        self.assertGreaterEqual(script.count('lastValueVisible:false,priceLineVisible:false'), 2)
        self.assertIn('lastValueVisible:true,priceLineVisible:true', script)

    def test_chart_catalog_keeps_raw_series_and_adds_verified_requested_items(self):
        script = (ROOT / 'assets/js/charts/economic-charts.js').read_text(encoding='utf-8')
        for removed in ('POLICY_EXPECTATION', 'EM_CAPACITY', 'US_SME_RISK', 'KR_SME_RISK', 'US_INFLATION'):
            self.assertNotIn(removed, script)
        for raw in ('US2Y', 'US10Y', 'HY_OAS', 'NFCI_CREDIT', 'EM_OAS', 'KR3Y', 'KR10Y', 'WTI', 'USDKRW', 'WEI', 'RRP', 'TGA', 'EMRATIO', 'KOSPI_PER', 'KOSPI_PBR', 'US_RETAIL_SALES', 'KR_EXPORT_DAILY_AVG'):
            self.assertIn(raw, script)
        self.assertIn("code:'DRALACBS'", script)
        self.assertIn("fallback:['policy_expectation_spreads','observation_date,treasury_2y_rate'", script)
        self.assertIn("fallback:['us_treasury_10y_daily','observed_on,treasury_10y_pct','observed_on','treasury_10y_pct']", script)

    def test_economic_chart_collection_is_automatic_only(self):
        automatic_workflow = (ROOT / '.github/workflows/economic-chart-data.yml').read_text(encoding='utf-8')
        automatic = (ROOT / 'backend/signals/economic_chart_automatic.py').read_text(encoding='utf-8')
        helpers = (ROOT / 'backend/signals/economic_chart_pipeline.py').read_text(encoding='utf-8')
        tracker = (ROOT / 'backend/tracking/check_targets.py').read_text(encoding='utf-8')

        self.assertIn('signals.economic_chart_automatic', automatic_workflow)
        self.assertIn('signals.business_credit_monthly', automatic_workflow)
        self.assertIn('signals.paynet_monthly', automatic_workflow)
        self.assertNotIn('backfill', automatic_workflow.lower())
        self.assertFalse((ROOT / '.github/workflows/economic-chart-backfill-once.yml').exists())
        self.assertFalse((ROOT / 'backend/signals/economic_chart_backfill.py').exists())
        self.assertIn('AUTOMATIC_DAILY_CALENDAR_DAYS', automatic)
        self.assertIn('AUTOMATIC_WEEKLY_WEEKS', automatic)
        self.assertIn('AUTOMATIC_MONTHLY_PERIODS', automatic)
        self.assertNotIn('economic_chart_backfill', automatic)
        self.assertNotIn('argparse', helpers)
        self.assertNotIn('choices=("automatic", "bootstrap")', helpers)
        self.assertIn('str(row["observation_date"]) not in existing', helpers)
        self.assertIn('check_collected_series_alerts(db, changed)', automatic)
        self.assertIn('!= "economic_chart"', tracker)
        self.assertIn('deliver_queued_alerts(db, targets)', tracker)

    def test_chart_reads_full_primary_history_and_merges_legacy_fallback_only_as_gap_cover(self):
        script = (ROOT / 'assets/js/charts/economic-charts.js').read_text(encoding='utf-8')
        pipeline = (ROOT / 'backend/signals/economic_chart_pipeline.py').read_text(encoding='utf-8')
        self.assertIn('"US10Y": ("DGS10", "D")', pipeline)
        self.assertIn('new Map([...fallbackRows,...primaryRows].map', script)
        self.assertIn("economic_chart_points", script)
        self.assertIn("US_POLICY_RATE_MID", script)
        self.assertIn("KR_POLICY_RATE", script)
        self.assertIn("lineType:'steps'", script)
        self.assertIn("window.LightweightCharts.LineType.WithSteps", script)

    def test_us_policy_rate_is_stored_as_decision_events_not_daily_rows(self):
        source = (ROOT / 'backend/sources/policy_rates.py').read_text(encoding='utf-8')
        automatic = (ROOT / 'backend/signals/policy_rate_automatic.py').read_text(encoding='utf-8')
        migration = (ROOT / 'supabase/migrations/20260913193000_replace_us_policy_rate_with_decision_events.sql').read_text(encoding='utf-8')
        self.assertIn('central_bank_policy_events', source)
        self.assertIn('DB:central_bank_policy_events', source)
        self.assertIn('"frequency": "E"', source)
        self.assertNotIn('fetch_fred_observations', source)
        self.assertNotIn('federalreserve.gov', source)
        self.assertIn('fetch_us_policy_rate_chart_rows(', automatic)
        self.assertIn('database, US_HISTORY_START, end, recent_limit=US_RECENT_DECISIONS', automatic)
        self.assertIn('recent_limit=US_RECENT_DECISIONS', automatic)
        self.assertFalse((ROOT / 'backend/signals/policy_rate_backfill.py').exists())
        self.assertFalse((ROOT / '.github/workflows/policy-rate-backfill.yml').exists())
        self.assertFalse((ROOT / 'backend/signals/policy_rate_chart_sync.py').exists())
        self.assertFalse((ROOT / '.github/workflows/policy-rate-chart-sync.yml').exists())
        self.assertIn("frequency in ('D', 'W', 'T', 'M', 'E')", migration)
        self.assertIn("where series_code = 'US_POLICY_RATE_MID'", migration)

    def test_korea_export_is_collected_incrementally(self):
        automatic = (ROOT / 'backend/signals/economic_chart_automatic.py').read_text(encoding='utf-8')
        source = (ROOT / 'backend/sources/korea_export_intramonth.py').read_text(encoding='utf-8')
        self.assertIn('fetch_snapshots(export_start_month, max_pages=6)', automatic)
        self.assertIn('KR_EXPORT_DAILY_AVG', automatic)
        self.assertIn('cumulative_export_musd - d10.cumulative_export_musd', source)
        self.assertIn('cumulative_workdays - d10.cumulative_workdays', source)
        self.assertIn('cumulative_export_musd - d20.cumulative_export_musd', source)
        self.assertIn('cumulative_workdays - d20.cumulative_workdays', source)
        self.assertFalse((ROOT / 'backend/signals/korea_export_backfill.py').exists())

    def test_core_series_include_fred_ecos_pykrx_and_derived_spreads(self):
        pipeline = (ROOT / 'backend/signals/economic_chart_pipeline.py').read_text(encoding='utf-8')
        automatic = (ROOT / 'backend/signals/economic_chart_automatic.py').read_text(encoding='utf-8')
        krx_source = (ROOT / 'backend/sources/krx_index_fundamentals.py').read_text(encoding='utf-8')
        for token in ('DGS2', 'DGS10', 'BAMLH0A0HYM2', 'NFCICREDIT', 'BAMLEMCBPIOAS', 'DCOILWTICO', 'DEXKOUS', 'WEI', 'RRPONTSYD', 'WTREGEN', 'EMRATIO'):
            self.assertIn(token, pipeline)
        self.assertIn('010200000', pipeline)
        self.assertIn('010210000', pipeline)
        self.assertIn('signals.policy_rate_automatic', automatic)
        self.assertIn('"DRALACBS": ("DRALACBS", "Q")', pipeline)
        self.assertIn('_fred_recent_rows(code, source_id, frequency, AUTOMATIC_DAILY_VALUES)', automatic)
        quarterly = (ROOT / 'supabase/migrations/20260913200000_add_quarterly_economic_chart_frequency.sql').read_text(encoding='utf-8')
        self.assertIn("'Q'", quarterly)
        self.assertIn('US10Y2Y', pipeline)
        self.assertIn('KR10Y3Y', pipeline)
        self.assertIn('from pykrx import stock', krx_source)
        self.assertIn('KOSPI_INDEX_TICKER = "1001"', krx_source)
        self.assertIn('"KOSPI_PER": ("PER", "D")', krx_source)
        self.assertIn('"KOSPI_PBR": ("PBR", "D")', krx_source)
        self.assertNotIn('MDCSTAT00702', pipeline)
        self.assertNotIn('earnings_v2.providers', pipeline)
        self.assertNotIn('SPCS20RSA', pipeline)


if __name__ == '__main__':
    unittest.main()
