alter table public.targets
  add column if not exists user_id uuid,
  add column if not exists last_checked_at timestamptz,
  add column if not exists last_error text;

create index if not exists targets_user_id_idx
  on public.targets (user_id);

create table if not exists public.alert_events (
  id bigint generated by default as identity primary key,
  target_id bigint not null references public.targets(id) on delete cascade,
  user_id uuid,
  previous_value text,
  current_value text not null,
  condition_type text not null,
  target_value numeric,
  channel text not null default 'kakao_self',
  status text not null check (status in ('sent', 'failed', 'skipped')),
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists alert_events_target_created_idx
  on public.alert_events (target_id, created_at desc);

create table if not exists public.notification_channels (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  channel text not null check (channel in ('kakao_self', 'email', 'push')),
  config jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, channel)
);

create table if not exists public.device_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  token text not null unique,
  platform text not null check (platform in ('web', 'android', 'ios')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.alert_events enable row level security;
alter table public.notification_channels enable row level security;
alter table public.device_tokens enable row level security;

