alter table public.central_bank_policy_events
  add column if not exists analysis_prompt_version text;

alter table public.central_bank_policy_events
  drop constraint if exists central_bank_policy_events_primary_reason_check,
  drop constraint if exists central_bank_policy_events_ai_primary_reason_check,
  drop constraint if exists central_bank_policy_events_admin_primary_reason_check,
  drop constraint if exists central_bank_policy_events_normalization_direction_check;

alter table public.central_bank_policy_events
  add constraint central_bank_policy_events_primary_reason_check check (
    primary_reason in ('inflation_fight', 'growth_overheat', 'recession_financial_stress', 'insurance_easing', 'normalization_hike', 'normalization_cut', 'uncertain')
  ),
  add constraint central_bank_policy_events_ai_primary_reason_check check (
    ai_primary_reason in ('inflation_fight', 'growth_overheat', 'recession_financial_stress', 'insurance_easing', 'normalization_hike', 'normalization_cut', 'uncertain')
  ),
  add constraint central_bank_policy_events_admin_primary_reason_check check (
    admin_primary_reason in ('inflation_fight', 'growth_overheat', 'recession_financial_stress', 'insurance_easing', 'normalization_hike', 'normalization_cut', 'uncertain')
  ),
  add constraint central_bank_policy_events_normalization_direction_check check (
    (ai_primary_reason <> 'normalization_hike' or action = 'hike')
    and (ai_primary_reason <> 'normalization_cut' or action = 'cut')
  );

create table if not exists public.central_bank_policy_analysis_history (
  id bigint generated by default as identity primary key,
  central_bank text not null,
  meeting_date date not null,
  analysis_prompt_version text,
  reanalyzed_to_version text not null,
  event_snapshot jsonb not null,
  archived_at timestamptz not null default now(),
  unique (central_bank, meeting_date, reanalyzed_to_version)
);

alter table public.central_bank_policy_analysis_history enable row level security;

comment on table public.central_bank_policy_analysis_history is
  'Immutable snapshots created before an FOMC statement is reanalyzed with a newer prompt version.';
