-- Operational state for resumable earnings collection.
--
-- One financial-period job represents one company/report period. Workers group
-- pending OpenDART jobs by business_year/report_code and send up to 100 company
-- codes in one provider request. This keeps scheduling granular while retaining
-- OpenDART's batch efficiency.

create table if not exists public.earnings_collection_checkpoints (
  source text not null check (source in ('open_dart', 'sec_edgar', 'krx', 'kis')),
  operation text not null check (char_length(trim(operation)) between 1 and 80),
  last_success_at timestamptz,
  cursor jsonb not null default '{}'::jsonb,
  consecutive_failures integer not null default 0 check (consecutive_failures >= 0),
  last_error text,
  updated_at timestamptz not null default now(),
  primary key (source, operation)
);

create table if not exists public.earnings_ingestion_jobs (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('open_dart', 'sec_edgar')),
  job_kind text not null check (job_kind in ('financial_period', 'filing_refresh')),
  company_id uuid not null references public.earnings_companies(id) on delete restrict,
  business_year integer check (business_year between 1900 and 2200),
  report_code text,
  reason text not null check (reason in ('live_filing', 'new_company', 'reentry_gap', 'repair')),
  priority smallint not null default 50 check (priority between 0 and 100),
  status text not null default 'pending' check (status in (
    'pending', 'running', 'retry', 'completed', 'failed'
  )),
  attempts smallint not null default 0 check (attempts >= 0),
  max_attempts smallint not null default 5 check (max_attempts > 0),
  available_at timestamptz not null default now(),
  claimed_at timestamptz,
  completed_at timestamptz,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    job_kind <> 'financial_period'
    or (business_year is not null and report_code in ('11013', '11012', '11014', '11011'))
  ),
  check (completed_at is null or status in ('completed', 'failed'))
);

-- Prevent only duplicate outstanding work. A completed period may be queued
-- again later for a correction or an explicit repair without deleting history.
create unique index if not exists earnings_ingestion_jobs_outstanding_uidx
  on public.earnings_ingestion_jobs (
    source, job_kind, company_id, business_year, coalesce(report_code, '')
  )
  where status in ('pending', 'running', 'retry');

create index if not exists earnings_ingestion_jobs_claim_idx
  on public.earnings_ingestion_jobs (source, status, priority desc, available_at, id)
  where status in ('pending', 'retry');

alter table public.earnings_collection_checkpoints enable row level security;
alter table public.earnings_ingestion_jobs enable row level security;

-- Operational queues are intentionally service-role only.
comment on table public.earnings_collection_checkpoints is
  'Last successful provider cursors used to recover automatically after missed schedules or long holidays.';
comment on table public.earnings_ingestion_jobs is
  'Resumable per-company earnings work; OpenDART workers batch compatible pending rows by period.';
