alter table public.central_bank_policy_events
  add column if not exists briefing jsonb,
  add column if not exists briefing_revision integer not null default 0,
  add column if not exists briefing_source_state jsonb not null default '{}'::jsonb,
  add column if not exists briefing_published_at timestamptz,
  add column if not exists briefing_updated_at timestamptz;

create table if not exists public.policy_briefing_alerts (
  central_bank text not null,
  meeting_date date not null,
  revision integer not null,
  alert_kind text not null check (alert_kind in ('new', 'update')),
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
  sent_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (central_bank, meeting_date, revision),
  foreign key (central_bank, meeting_date)
    references public.central_bank_policy_events (central_bank, meeting_date)
    on delete cascade
);

alter table public.policy_briefing_alerts enable row level security;

comment on column public.central_bank_policy_events.briefing is
  'Official FOMC materials-derived Korean briefing generated by the versioned policy prompt.';
comment on column public.central_bank_policy_events.briefing_source_state is
  'Source availability and immutable meeting-time context used to prevent duplicate revisions.';
comment on table public.policy_briefing_alerts is
  'Transactional outbox for idempotent NEW/UPDATE FOMC briefing Kakao notifications.';
