-- News sentiment domain. Source article text, titles, images and URLs are not
-- persisted; only short derived event metadata and aggregate results are kept.

create table if not exists public.news_events (
  id uuid primary key default gen_random_uuid(),
  event_key text not null unique,
  event_date date not null,
  event_at timestamptz,
  summary text not null,
  category text not null check (category in ('macro', 'finance', 'international')),
  impact_scope text not null default 'market',
  transmission_channels text[] not null default '{}',
  market_relevance numeric(4, 3) not null default 0 check (market_relevance between 0 and 1),
  short_term_impact text not null check (short_term_impact in ('positive', 'neutral', 'negative', 'uncertain')),
  five_day_impact text not null check (five_day_impact in ('positive', 'neutral', 'negative', 'uncertain')),
  confidence numeric(4, 3) not null default 0 check (confidence between 0 and 1),
  source_count integer not null default 0 check (source_count >= 0),
  analysis_version text not null default 'v1',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists news_events_event_date_idx
  on public.news_events (event_date desc, event_at desc);

create index if not exists news_events_impact_idx
  on public.news_events (short_term_impact, event_date desc);

create table if not exists public.news_event_sources (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.news_events(id) on delete cascade,
  source_name text not null check (source_name in ('yonhap', 'hankyung', 'gdelt')),
  source_item_hash text not null,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  unique (source_name, source_item_hash)
);

create index if not exists news_event_sources_event_idx
  on public.news_event_sources (event_id);

create table if not exists public.news_daily_sentiment (
  event_date date primary key,
  positive_count integer not null default 0 check (positive_count >= 0),
  neutral_count integer not null default 0 check (neutral_count >= 0),
  negative_count integer not null default 0 check (negative_count >= 0),
  uncertain_count integer not null default 0 check (uncertain_count >= 0),
  included_event_count integer not null default 0 check (included_event_count >= 0),
  weighted_positive numeric(10, 4) not null default 0,
  weighted_neutral numeric(10, 4) not null default 0,
  weighted_negative numeric(10, 4) not null default 0,
  analysis_version text not null default 'v1',
  generated_at timestamptz not null default now()
);

create table if not exists public.news_event_feedback (
  event_id uuid primary key references public.news_events(id) on delete cascade,
  short_term_override text check (short_term_override in ('positive', 'neutral', 'negative', 'uncertain')),
  five_day_override text check (five_day_override in ('positive', 'neutral', 'negative', 'uncertain')),
  reason text not null,
  reviewed_by uuid not null references auth.users(id) on delete restrict,
  reviewed_at timestamptz not null default now()
);

alter table public.news_events enable row level security;
alter table public.news_event_sources enable row level security;
alter table public.news_daily_sentiment enable row level security;
alter table public.news_event_feedback enable row level security;

-- News data is exposed only through authenticated Edge Functions so that the
-- guest 10-day window and future entitlement rules cannot be bypassed.

comment on table public.news_events is 'Derived event records only; no article titles, bodies, images or URLs.';
comment on table public.news_daily_sentiment is 'Daily chart aggregates; uncertain events are tracked separately.';
